apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: spork1
    appstudio.openshift.io/component: node-express-hello-hak0
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: node-express-hello-hak0
  namespace: user1-tenant
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_spork-madness_node-express-hello
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/spork-madness/node-express-hello
