apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello-hak0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello-hak0
    app.kubernetes.io/part-of: spork1
  name: node-express-hello-hak0
  namespace: user1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: node-express-hello-hak0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: node-express-hello-hak0
    spec:
      containers:
      - image: quay.io/arewm/sporks:NA_QT-node-express-hello-hak0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
