apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-hagz
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/arewm/sporks@sha256:d0b8ba13209c164f72b50cd9bfc9ba877713ab5fa85ff1978c31116105665813
        name: my-go
        resources: {}
status: {}
